name: learn-github-actions
on: 
  push:
    branches:
      - main
jobs:
  install dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm i
  build:
    runs-on: ubuntu-latest
    needs: install dependencies
    steps:
      - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run deply script
        run: ./deploy.sh
        shell: bash