name: deploy site
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: "Install dependencies"
        run: npm i
      - name: "Build site"
      - run: npm run build
      - name: Run deploy script
        run: ./deploy.sh
        shell: bash
