name: deploy site
on: 
  push:
    branches:
      - main
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm i
  build:
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - run: npm run build
      

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run deploy script
        run: ./deploy.sh
        shell: bash